### ISSUE TITLE
No symbol named '' found in system symbol set in stdout

### ISSUE THREAD

**Issue by saladd-bu** [bartreardon/swiftDialog#153] opened 2022-08-10 13:46 UTC
When running Dialog via json input or something as simple as `dialog --title "Hello"` on macOS Ventura Customer Seed (22A5321d), Dialog is outputting the below error to stdout, which must then be handled if you are parsing selections, etc.

Tested with both Dialog 1.11.2-2988 and 1.11.1-2839.

`No symbol named '' found in system symbol set`

Thus far, I have not been able to reproduce this with Monterey 12.5.

Would it be possible to look at:
1. The nature of the error
2. Directing this to stderr for cleaner output

Thanks!

**Comment by bartreardon** [comment] 2022-08-11 09:07
Yeah, this is an issue in Ventura only and I'm not certain it isn't because as a beta OS it has extra debugging and logging present. 

The issue is being generated by SwiftUI so I can't re-direct unfortunately. It's a known issue though so I'll be keeping my eye on it.

**Comment by bartreardon** [comment] 2022-11-18 00:02
Fixed in 2.0

**Closed by bartreardon** 2022-11-18 00:02 UTC
Labels: bug
